[package]
name = "elgato-streamdeck-async"
description = "Async HidApi driver for Elgato Stream Deck devices"
authors = ["TheJebForge", "nekename", "HRKings"]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/HRKings/rust-streamdeck-async"
license = "MPL-2.0"

[dependencies]
hidapi = "2.6"
image = { version = "0.25", default-features = false, features = [ "bmp","jpeg" ] }
tokio = { version = "1.47.1", optional = true }
tokio-stream = { version = "0.1.17", optional = true }
strum = { version = "0.27", features = ["derive"], optional = true }

[features]
async = ["tokio", "tokio/sync", "tokio/rt-multi-thread", "tokio/time"]
stream = ["async", "dep:tokio-stream"]
strum = ["dep:strum"]
default = ["async"]

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1.17"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
